import collections
import glob
import yaml

from datasets import Dataset
import evaluate
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import *
import numpy as np
import pandas as pd
import torch
import gc
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, cohen_kappa_score, f1_score, precision_score, recall_score, average_precision_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForTokenClassification, DataCollatorWithPadding, TrainingArguments, Trainer, pipeline
from transformers import DebertaV2ForSequenceClassification, DebertaV2Tokenizer
from transformers import EarlyStoppingCallback
import torch.nn.functional as F
import torch.nn as nn


ENG_STOPWORDS = set(stopwords.words('english'))
CONFIG = yaml.safe_load(open("config.yml"))

class ArticleClassifier(object):
    """
    Base class for relevance classification of text data. 
    Probably don't try to use the base class for anything.
    """
    def __init__(self):
        """
        Sets up a classifier and a (optionally tuneable) threshold for classification
        """
        self.classifier = None # some function that classifies text
        self.threshold = 0.0 # in case we need to tune bias or whatever

    def fit(self, X_train, y_train):
        """
        Will be unique to every child class
        """
        pass

    def accuracy_pr_kappa(self, X_test, y_test):
        """
        Runs the classifier on X_test, which should be an array of texts.
        Compares the classifications it gets to y_test, which is the list of ground truth categorizations for X_test.

        Returns a dict of metrics:
            accuracy
            precision
            recall
            F1 score
            Cohen's Kappa
        """
        guess = self.predict(X_test) # prediction step
        accuracy = accuracy_score(y_test, guess)
        precision = precision_score(y_test, guess, zero_division=0)
        recall = recall_score(y_test, guess, zero_division=0)
        my_f1_score = f1_score(y_test, guess, zero_division=0)
        kappa = cohen_kappa_score(y_test, guess)
        # return a dict of metrics wow
        return {'accuracy': accuracy, 
                'precision': precision, 
                'recall': recall, 
                'f1': my_f1_score, 
                'cohen_kappa': kappa
                }

    def predict(self, X_data):
        """
        Returns a list of classifier predictions; assumes self.classifier is a function/callable that takes in a string.
        """
        return [self.classifier(x) for x in X_data]


class WordRelevanceClassifier(ArticleClassifier):
    """
    Given a list of words and a threshold number of times they should appear in order for the article/keyword list to be considered relevant,
    tag an article or keyword list for relevance.
    """
    def __init__(self, threshold=0, source='keywords', keywords=set(['mpox', 'monkeypox'])):
        """
        Instantiate the class.

        Params:
            threshold: the min number of words that should appear in order for the article/keyword list to be counted as relevant. 
                for keywords, we see each keyword listed once per article. for article text, a word may be repeated and therefore count twice.
            source: one of {keywords, text}. keywords = the keyword list generated by newspaper4k; text = the raw article text
            keywords: a set of lowercase strings corresponding to some keywords that ought to be predictive of relevance.
        """
        self.mpox_keywords = keywords
        self.threshold = threshold
        if source == 'keywords':
            # make an anonymous function that splits up the keyword list (which is a literal of a list) and checks how many of them are in our keyword list
            self.classifier = lambda b: len(set([w.strip() for w in b.lower()[2:-2].split("', '")]).intersection(self.mpox_keywords)) > self.threshold
        elif source == 'text':
            # checks how many times our keywords show up in our article text and compares it to self.threshold.
            self.classifier = lambda b: self.get_counts_from_text(b) > self.threshold
        else:
            raise ValueError("good luck trying to analyze that column buddy")

    def get_counts_from_text(self, text):
        """
        Get the number of times our keywords show up in the text (X instances of word Y = X points)

        text: a string (article text)

        returns: the total number of keyword hits as explained above.
        """
        ct = collections.Counter([w.strip() for w in text.lower().split() if w not in ENG_STOPWORDS])
        tot_hits = sum([ct[k] for k in self.mpox_keywords])
        return tot_hits

    def fit(self, X_train, y_train):
        """
        We aren't actually fitting anything here lol
        """
        raise NotImplementedError("This function is too dumb to have a train function!")

class NBClassifier(ArticleClassifier):
    """
    Naive Bayes classifier for article relevance; can look at keywords or article text.
    """
    def __init__(self, input_type='keywords'):
        """
        Instantiates the object

        Params:
        input_type: lets us know if we're looking at keywords or article text ({'keywords', 'text'} and all others are invalid)
        """
        self.classifier = MultinomialNB()  # will set class_weight in fit()
        self.vectorizer = CountVectorizer(
            strip_accents = 'ascii', 
            lowercase = True,
            stop_words='english',
        )
        if input_type == 'keywords':
            self.input_parser = lambda b: b.lower()[2:-2].replace(',', ' ')
        elif input_type == 'text':
            self.input_parser = lambda b: ' '.join([s for s in b.lower().split() if s not in ENG_STOPWORDS])
        else:
            raise ValueError("good luck trying to analyze that column buddy")

    def fit(self, X_train, y_train):
        """
        Given X_train (list of strings, either keywords or article text), and y_train (binary vector),
        train a Naive Bayes classifier to label the strings for relevance.
        """
        # Apply the input parser here so MultiFrameClassifier just passes raw text
        X_proc = [self.input_parser(x) for x in X_train]
        self.vectorizer_fit = self.vectorizer.fit(X_proc)
        x_train_transformed = self.vectorizer_fit.transform(X_proc)
        
        # Compute class weights (same formula as DeBERTa)
        y_train = np.array(y_train).astype(int)
        n_pos = int((y_train == 1).sum())
        n_neg = int((y_train == 0).sum())
        N = len(y_train)
        
        # Balanced class weights
        w_neg = N / (2.0 * max(n_neg, 1))
        w_pos = N / (2.0 * max(n_pos, 1))
        
        # MultinomialNB uses sample_weight (not class_weight)
        sample_weights = np.where(y_train == 1, w_pos, w_neg)
        
        print(f"  NB: w_neg={w_neg:.2f}, w_pos={w_pos:.2f}, n_pos={n_pos}, n_neg={n_neg}")
        
        self.classifier = self.classifier.fit(x_train_transformed, y_train, sample_weight=sample_weights)

    def predict(self, X_data):
        """
        Runs the X_data (list of strings) through the vectorizer and then classifies the resulting count vectors.
        """
        X_proc = [self.input_parser(x) for x in X_data]
        x_transformed = self.vectorizer_fit.transform(X_proc)
        return self.classifier.predict(x_transformed)

    def frac_predict(self, X_data):
        """
        Runs the X_data (list of strings) through the vectorizer and then produces a probability for the resulting count vectors.
        """
        X_proc = [self.input_parser(x) for x in X_data]
        x_transformed = self.vectorizer_fit.transform(X_proc)
        proba = self.classifier.predict_proba(x_transformed)[:, 1]  # P(y=1)
        return proba



def effective_num_weight(n_pos, n_neg, beta=0.999):
    """
    Compute class weights using the 'effective number of samples' method.
    Returns a tensor [w_neg, w_pos] normalized to sum to 2.
    """
    def calc(n):
        return (1 - beta) / (1 - beta**max(n, 1))

    w_pos = calc(n_pos)
    w_neg = calc(n_neg)
    Z = w_pos + w_neg
    w_pos = w_pos / Z * 2.0
    w_neg = w_neg / Z * 2.0
    return torch.tensor([w_neg, w_pos], dtype=torch.float)


class FocalLoss(nn.Module):
    """
    Focal loss with optional class weights alpha (tensor [w_neg, w_pos]).
    """
    def __init__(self, alpha=None, gamma=2.0):
        super().__init__()
        self.alpha = alpha  # torch.tensor or None
        self.gamma = gamma

    def forward(self, logits, labels):
        # move alpha to correct device if provided
        if self.alpha is not None:
            alpha = self.alpha.to(logits.device)
        else:
            alpha = None

        ce = F.cross_entropy(logits, labels, weight=alpha, reduction="none")
        pt = torch.exp(-ce)  # pt = exp(-CE) = predicted prob for the true class
        loss = (1 - pt) ** self.gamma * ce
        return loss.mean()

class WeightedCETrainer(Trainer):
    """
    Trainer that uses Focal Loss with class weights for imbalance.
    """
    def __init__(self, class_weights=None, gamma=2.0, **kwargs):
        super().__init__(**kwargs)
        self.class_weights = class_weights  # torch.tensor([w_neg, w_pos])
        # we construct the focal loss object here; alpha will be moved to device in forward()
        self.loss_fn = FocalLoss(alpha=class_weights, gamma=gamma)

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits  # (B, 2)

        loss = self.loss_fn(logits, labels)

        return (loss, outputs) if return_outputs else loss


class DeBERTaClassifier(ArticleClassifier):
    """
    Text classifier that trains a DeBERTa (deberta-v3-base specifically) model to classify text based on a training set.
    """
    def __init__(self, rel_label, run_save_dir, device='cpu', lr=2e-5):
        """
        Initialize a DeBERTa-based classifier.

        Parameters:
        rel_label: string; the label of the characteristic we are training the classifier to detect (could be a frame or a relevance tag, for example)
        run_save_dir: string; directory to save the pytorch model files to
        device: string or int; defaults to 'cuda' to use GPU.
        lr: float; learning rate for the optimizer.
        """
        self.run_save_dir = run_save_dir
        self.rel_label = rel_label
        torch.set_float32_matmul_precision("medium")
        self.tokenizer = DebertaV2Tokenizer.from_pretrained(
            "microsoft/deberta-v3-base", model_max_length=512
        )
        self.model = DebertaV2ForSequenceClassification.from_pretrained(
            "microsoft/deberta-v3-base", num_labels=2
        )
        self.training_args = TrainingArguments(
            output_dir=f"{self.run_save_dir}/saved-models-deberta-{rel_label.replace(' ', '_')}",
            overwrite_output_dir=True,
            eval_strategy="epoch",  
            save_strategy="epoch",
            push_to_hub=False,
            num_train_epochs=10,
            per_device_train_batch_size=2,
            per_device_eval_batch_size=2,
            learning_rate=lr,
            load_best_model_at_end=True,
            eval_steps=25,
            save_steps=25,
            save_total_limit=3,
            save_on_each_node=True,
            metric_for_best_model="pr_auc",   # select on PR-AUC
            greater_is_better=True,
            weight_decay=0.01,
            warmup_ratio=0.1,
            max_grad_norm=1.0,
            gradient_accumulation_steps=2,
        )
        self.device = device
        self.model.to(self.device)


    def compute_metrics(self, eval_pred):
        """
        Compute performance metrics for the model.

        Inputs:
        eval_pred: tuple of (logits, labels)
          logits: array of vectors of length 2 with float probabilities for each class. 
          labels: binary ground truth labels. same length as logits.

        Returns:
          performance metrics comparing the predictions in logits to the ground truth labels.
        """
        logits, labels = eval_pred
        probs_pos = torch.softmax(torch.tensor(logits), dim=-1).numpy()[:, 1]
        labels = np.array(labels)
        preds = (probs_pos >= 0.5).astype(int)
        return {
            "pr_auc": average_precision_score(labels, probs_pos),
            "f1_macro": f1_score(labels, preds, average="macro")
        }

    def load_best(self):
        """
        Load the most recent saved model onto GPU (we save the top 3 models & pick the most recently saved model, in terms of training epochs.)
        """
        pattern = f"{self.run_save_dir}/saved-models-deberta-{self.rel_label.replace(' ', '_')}/checkpoint-*"
        saved = sorted([d for d in glob.glob(pattern)], key=lambda b: int(b.split('-')[-1]))
        best = saved[-1]  # latest
        self.model = DebertaV2ForSequenceClassification.from_pretrained(best).to(self.device)

    def make_dataset(self, df):
        """
        Convert a dataframe of text data with labels into a dataset that's compatible with the huggingface model.

        Inputs:
        df: pandas DataFrame with columns self.rel_label, title, and text.

        Returns:
        Dataset object w/ tokenized text.
        """
        df['label'] = df[self.rel_label]
        dataset = Dataset.from_pandas(df[['title', 'text', 'label']])
        return dataset.map(self.tokenize)

    def tokenize(self, examples):
        """
        Tokenize input text, joining title and article text with a newline character first.

        Inputs:
          examples: dict-like with keys title and text.

        Returns:
          tokenized text tokenized using the model specified in the __init__ function.
        """
        return self.tokenizer(examples["title"] + '\n' + examples['text'], padding="max_length", truncation=True)

    def train_with_validation(self, df_train, df_val):
        """
        Trains a DeBERTa model using df_train as the training set and df_val as the validation set. 
        Prints metrics and losses every 25 epochs.

        Inputs:
        df_train: pandas dataframe containing training data
        df_val: pandas dataframe containing validation data. 
        """
        train_tokenized_datasets = self.make_dataset(df_train)
        val_tokenized_datasets = self.make_dataset(df_val)
        trainer = Trainer(
            model=self.model,
            args=self.training_args,
            train_dataset=train_tokenized_datasets,
            eval_dataset=val_tokenized_datasets,
            compute_metrics=self.compute_metrics,
        )
        trainer.train()

    def frac_predict(self, df_test):
        """
        Predict the probabilities of examples matching the label for a dataframe of examples.

        Inputs:
        df_test: Pandas DataFrame of test data with columns title and text at minimum.

        Returns:
        array of classification probabilities with same length as df_test.
        """
        ds = Dataset.from_pandas(df_test[['title','text']])
        self.model.eval()
        out = []
        for ex in ds:
            text = f"{ex['title']}.\n{ex['text']}"
            inputs = self.tokenizer(text, padding=True, truncation=True, return_tensors="pt").to(self.device)
            with torch.no_grad():
                logits = self.model(**inputs).logits
            p = torch.softmax(logits, dim=-1)[:, 1].item()
            out.append(p)
        return np.array(out)
        
    def predict(self, df_test, threshold=0.5):
        """
        Given a dataframe of examples, predict binary classifications for each example.

        Inputs:
        df_test: Pandas DataFrame of test data with columns title and text at minimum.

        Returns:
        array of Boolean classifications with same length as df_test.
        """
        probs = self.frac_predict(df_test)
        return (probs >= threshold).astype(int)


class BERTClassifier(ArticleClassifier):
    """
    Text classifier that trains a BERT (bert-base-cased specifically) model to classify text based on a training set.
    """
    def __init__(self, rel_label, run_save_dir, device='cpu'):
        """
        Initialize a DeBERTa-based classifier.

        Parameters:
        rel_label: string; the label of the characteristic we are training the classifier to detect (could be a frame or a relevance tag, for example)
        run_save_dir: string; directory to save the pytorch model files to
        device: string or int; defaults to 'cuda' to use GPU.
        lr: float; learning rate for the optimizer.
        """
        self.rel_label = rel_label
        self.device = device
        self.run_save_dir = run_save_dir
        torch.set_float32_matmul_precision("medium")
        self.tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-cased")
        self.model = AutoModelForSequenceClassification.from_pretrained("google-bert/bert-base-cased", num_labels=2)
        self.metric = evaluate.load("f1")
        self.training_args = TrainingArguments(
            output_dir="{}/saved-models-bert-{}".format(self.run_save_dir, rel_label.replace(' ', '_')),
            overwrite_output_dir=True,
            eval_strategy="epoch",
            save_strategy='epoch',
            push_to_hub=False,
            num_train_epochs=20,
            per_device_train_batch_size=2,
            per_device_eval_batch_size=2,
            learning_rate=2e-5,
            load_best_model_at_end=True,
            eval_steps = 25,
            save_steps=25,
            save_total_limit = 3,
            save_on_each_node=True,
            metric_for_best_model='pr_auc',
            greater_is_better=True,
            weight_decay=0.01,
            warmup_ratio=0.1,
            max_grad_norm=1.0,
            gradient_accumulation_steps=2,
        )
        self.model.to(self.device)
        
    def compute_metrics(self, eval_pred):
        """
        Compute performance metrics for the model.

        Inputs:
        eval_pred: tuple of (logits, labels)
          logits: array of vectors of length 2 with float probabilities for each class. 
          labels: binary ground truth labels. same length as logits.

        Returns:
          performance metrics comparing the predictions in logits to the ground truth labels.
        """
        logits, labels = eval_pred
        probs_pos = torch.softmax(torch.tensor(logits), dim=-1).numpy()[:, 1]
        labels = np.array(labels)
        preds = (probs_pos >= 0.5).astype(int)
        return {
            "pr_auc": average_precision_score(labels, probs_pos),
            "f1_macro": f1_score(labels, preds, average="macro")
        }
        
    def make_dataset(self, df):
        """
        Convert a dataframe of text data with labels into a dataset that's compatible with the huggingface model.

        Inputs:
        df: pandas DataFrame with columns self.rel_label, title, and text.

        Returns:
        Dataset object w/ tokenized text.
        """
        df['label'] = df[self.rel_label]
        dataset = Dataset.from_pandas(df[['title', 'text', 'label']])
        return dataset.map(self.tokenize)
        
    def tokenize(self, examples):
        """
        Tokenize input text, joining title and article text with a newline character first.

        Inputs:
          examples: dict-like with keys title and text.

        Returns:
          tokenized text tokenized using the model specified in the __init__ function.
        """
        return self.tokenizer(examples["title"] + '\n' + examples['text'], padding="max_length", truncation=True)
            
    def train_with_validation(self, df_train, df_val):
        """
        Trains a DeBERTa model using df_train as the training set and df_val as the validation set. 
        Prints metrics and losses every 25 epochs.

        Inputs:
        df_train: pandas dataframe containing training data
        df_val: pandas dataframe containing validation data. 
        """
        train_tokenized_datasets = self.make_dataset(df_train)
        val_tokenized_datasets = self.make_dataset(df_val)
        trainer = Trainer(
            model=self.model,
            args=self.training_args,
            train_dataset=train_tokenized_datasets,
            eval_dataset=val_tokenized_datasets,
            compute_metrics=self.compute_metrics,
        )
        trainer.train()
        
    def load_best(self):
        """
        Load the most recent saved model onto GPU (we save the top 3 models & pick the most recently saved model, in terms of training epochs.)
        """
        save_dir = "{}/saved-models-bert-{}/checkpoint-*".format(self.run_save_dir, self.rel_label.replace(' ', '_'))
        saved_best = sorted([d for d in glob.glob(save_dir)], key=lambda b: int(b.split('-')[-1]))[-1]
        print(saved_best)
        self.model = AutoModelForSequenceClassification.from_pretrained(saved_best)
        self.model.to(self.device)

    def frac_predict(self, df_test):
        """
        Predict the probabilities of examples matching the label for a dataframe of examples.

        Inputs:
        df_test: Pandas DataFrame of test data with columns title and text at minimum.

        Returns a 1D np.array of P(y=1) for each example.
        """
        test_dataset = Dataset.from_pandas(df_test[['title', 'text']])
        self.model.eval()
        probs = []

        for example in test_dataset:
            text = f"{example['title']}.\n{example['text']}"
            inputs = self.tokenizer(
                text,
                padding=True,
                truncation=True,
                return_tensors="pt"
            ).to(self.device)
            with torch.no_grad():
                outputs = self.model(**inputs)
            logits = outputs.logits  # shape (1,2)
            p1 = torch.softmax(logits, dim=-1)[:, 1].item()  # P(class 1)
            probs.append(p1)

        return np.array(probs)
        
    def predict(self, df_test, threshold=0.5):
        """
        Given a dataframe of examples, predict binary classifications for each example.

        Inputs:
        df_test: Pandas DataFrame of test data with columns title and text at minimum.

        Returns:
        array of Boolean classifications with same length as df_test.
        """
        probs = self.frac_predict(df_test)
        return (probs >= threshold).astype(int)


class MultiCriterionClassifier(ArticleClassifier):
    """
    Combine the opinions of an arbitrary set of classifiers to arrive at a more informed conclusion.
    """
    def __init__(self, classifiers_with_bools, threshold=None):
        """
        Initialize the classifier.

        Inputs:
            classifers_with_bools: list of (classifier, score_if_relevant) tuples of a RelevanceClassifier object and a boolean value.
            score_if_relevant should be one of {True, False} and should be the score that turns up when an item is relevant.
            threshold: must satisfy strictly more than this number of classifiers in order to be marked relevant.
        """
        self.values_if_relevant = []
        self.classifiers = []
        
        # if no threshold is expressed, everyone has to agree
        if threshold is None:
            self.threshold = len(classifiers_with_bools) - 1
        else:
            # you can also set your own threshold
            self.threshold = threshold

        for clf, val_if_relevant in classifiers_with_bools:
            self.values_if_relevant.append(val_if_relevant)
            self.classifiers.append(clf)

    def predict(self, X_data):
        """
        Given a tuple of inputs as (input_for_clf_1, input_for_clf_2, ...input_for_clf_k),
        run each classifier against its input and then check whether enough classifiers are satisfied with the input's relevance.
        Return pred, a vector of bools.
        """
        pred_bools = np.array([c.predict(x) for c, x in zip(self.classifiers, X_data)])
        pred_scores = [np.sum(row == self.values_if_relevant) for row in pred_bools.T]
        pred = [p > self.threshold for p in pred_scores]
        return pred 

class MultiFrameClassifier(ArticleClassifier):
    """
    Classify a dataset that has multiple frames; builds a dedicated sub-classifier for each frame.
    """
    def __init__(self, frames, run_save_dir=None, clf_type='NB', device='cpu', lr=5e-5):
        """
        Inititalize a MultiFrameClassifier object.

        Inputs:
        frames: list of strings representing the frames being detected.
        run_save_dir: str or None; base path to directory where models will be saved (if we're using a pytorch model). 
          default value None. required for BERT/DeBERTa models.
        clf_type: string in {'NB', 'BERT', 'DeBERTa'}; defaults to 'NB'
        device: string or int; defaults to 'cuda' and specifies whether to use GPU or CPU for pytorch (if used)
        lr: float; learning rate; only relevant for BERT and DeBERTa. 
        """
        self.frames = frames
        self.clf_type = clf_type
        if self.clf_type == "NB":
            self.frame_classifiers = {frame: NBClassifier(input_type='text') for frame in self.frames}
        elif self.clf_type == "BERT":
            if run_save_dir is None:
                raise ValueError("need a run save dir")
            else:
                self.frame_classifiers = {frame: BERTClassifier(frame, run_save_dir, device) for frame in self.frames}
        elif self.clf_type == 'DeBERTa':
            if run_save_dir is None:
                raise ValueError("need a save dir")
            else:
                self.frame_classifiers = {frame: DeBERTaClassifier(frame, run_save_dir, device, lr=lr) for frame in self.frames}
            
    def fit(self, X_train, ys_train, X_val=None, ys_val=None):
        """
        Given training data, fit the model to the training data. Validation data is required if using BERT/DeBERTa.

        Inputs:
        X_train: dataframe of text training examples. should include columns 'title' and 'text'.
        ys_train: iterable, likely dataframe, of framing labels. should have one column corresponding to each frame and have the same length as X_train.
        X_val: dataframe of text validation examples. optional for NB and required for the BERT-based models.
        ys_val: iterable, likely dataframe, of framing labels. should have one column corresponding to each frame and have the same length as X_val.
          optional for NB and required for the BERT-based models.

        """

        if self.clf_type == "NB":
            for frame in self.frames:
                y = ys_train[frame].values.astype(int)
                print(f"[{frame}] NB training: n_pos={int((y==1).sum())}, n_neg={int((y==0).sum())}")
                # Pass the Series directly so NBClassifier can apply input_parser
                self.frame_classifiers[frame].fit(X_train, y)

        elif self.clf_type == "DeBERTa" or self.clf_type == "BERT":

            if X_val is None or ys_val is None:
                raise ValueError("DeBERTa requires validation data (X_val, ys_val).")
             
            for frame in self.frames:

                gc.collect()
                torch.cuda.empty_cache()

                df_train = pd.concat((X_train, ys_train), axis=1)
                df_val   = pd.concat((X_val,   ys_val),   axis=1)

                y = ys_train[frame].values
                n_pos = int((y == 1).sum())
                n_neg = int((y == 0).sum())

                # *** move model to cuda JUST for this frame ***
                model = self.frame_classifiers[frame].model.to("cuda")
                device = torch.device("cuda")

                cw = effective_num_weight(n_pos, n_neg).to(device)

                train_ds = self.frame_classifiers[frame].make_dataset(df_train)
                val_ds   = self.frame_classifiers[frame].make_dataset(df_val)

                print(f" {self.clf_type} [{frame}] w_neg={cw[0].item():.2f}, w_pos={cw[1].item():.2f}, "
                    f"n_pos={n_pos}, n_neg={n_neg}")

                trainer = WeightedCETrainer(
                    model=self.frame_classifiers[frame].model,
                    args=self.frame_classifiers[frame].training_args,
                    train_dataset=train_ds,
                    eval_dataset=val_ds,
                    compute_metrics=self.frame_classifiers[frame].compute_metrics,
                    class_weights=cw,
                    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
                )
                trainer.train()

                # *** move model back to CPU and drop trainer to free GPU ***
                self.frame_classifiers[frame].model = model.to("cpu")
                del trainer
                gc.collect()
                torch.cuda.empty_cache()
                
    def predict(self, X_pred):
        """
        Given a dataframe of examples, produce binary classification predictions for each frame.

        Inputs:
        X_pred: dataframe of text exapmles. should include columns 'title' and 'text'.

        Outputs:
        dict mapping each frame to a list of boolean values indicating whether that frame is present. the lists are aligned with the ordering in X_pred.
        """
        return {frame: self.frame_classifiers[frame].predict(X_pred) for frame in self.frames}

    def frac_predict(self, X_pred):
        """
        Given a dataframe of examples, produce fractional classification probabilities for each frame.

        Inputs:
        X_pred: dataframe of text exapmles. should include columns 'title' and 'text'.

        Outputs:
        dict mapping each frame to a list of floats indicating the probability that that frame is present. the lists are aligned with the ordering in X_pred.
        """
        return {frame: self.frame_classifiers[frame].frac_predict(X_pred) for frame in self.frames}
        
    def accuracy_pr_kappa(self, X_test, ys_test):
        """
        Runs the classifier on X_test, which should be an array of texts.
        Compares the classifications it gets to y_test, which is the list of ground truth categorizations for X_test.

        Returns a dict of metrics:
            accuracy
            precision
            recall
            F1 score
            Cohen's Kappa
        """
        preds = self.predict(X_test)
        metrics = {}
        for frame in self.frames:
            guess = preds[frame]
            y_test = ys_test[frame]
            accuracy = accuracy_score(y_test, guess)
            precision = precision_score(y_test, guess, zero_division=0)
            recall = recall_score(y_test, guess, zero_division=0)
            my_f1_score = f1_score(y_test, guess, zero_division=0)
            kappa = cohen_kappa_score(y_test, guess)

            metrics[frame] = {
                'accuracy': accuracy,
                'precision': precision,
                'recall': recall,
                'f1': my_f1_score,
                'kappa': kappa,
            }
        return metrics
     
