---
title: "playground"
format: pdf
editor: visual
editor_options: 
  chunk_output_type: console
---

# Load libraries

```{r}
library(ggplot2)
library(Metrics)
library(irr)

```

# Agreement between different annotators

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false
#| output: false

calculate_scores <- function(dlist, A1, A2, column_A1, column_A2, column_match = "stories_id", dropNA = T, silent = T)
{
  dfA1 <- dlist[[A1]]
  dfA2 <- dlist[[A2]]

  kdf1 <- merge(dfA1, dfA2, by.x = column_match, by.y = column_match, all = F)

  #if column names for A1 and A2 are same
  if(column_A1 == column_A2)
  {
    kdf <- kdf1[,c(paste0(column_A1, ".x"), paste0(column_A2, ".y"))]
  }

  else
  {
    kdf <- kdf1[,c(column_A1, column_A2)]
  }

  colnames(kdf) <- c("A1", "A2")

  if(dropNA)
  {
    kdf <- kdf[complete.cases(kdf),]
  }

  klist <- kappa2(kdf) #kappa calculation
  k <- round(klist$value, 2) #Cohen's Kappa

  acc <- round(accuracy(kdf[,1],kdf[,2]),2) #accuracy
  prec <- round(precision(kdf[,1], kdf[,2]), 2) #precision
  rec <- round(recall(kdf[,1], kdf[,2]), 2) #recall
  F1 <- round(2*prec*rec/(prec + rec), 2) #F1 score cos the f1 func is broken

  metric_vec <- c(acc, k, F1, prec, rec)
  
  if(silent == F)
  {
    print(paste0("Accuracy is ", acc, "; Cohen's kappa is ", k, "; F1 score is ",F1,
               "; Precision is ", prec, "; Recall is ", rec))
  }

  return(metric_vec)
}

```

## Relevance

```{r}
load("Labelled/Relevance_test.RData")

raters <- c("a1_r2", "a2_r2", "naive_bayes", "bert", "deberta", "llama_fine-tuned",
            "claude_zero-shot", "gpt-oss_zero-shot")

kappa_df <- expand.grid("Rater_1" = raters,
                        "Rater_2" = raters,
                        "kappa_val" = NA,
                        stringsAsFactors = F)

for(i in 1:nrow(kappa_df))
{
  if(kappa_df$Rater_1[i]!=kappa_df$Rater_2[i])
  {
    vec <- calculate_scores(relevance_list, kappa_df$Rater_1[i], kappa_df$Rater_2[i], "relevance", "relevance", column_match = "stories_id")
    
    kappa_df$kappa_val[i] <- vec[2]
  }
}

kappa_df$Rater_1 <- factor(kappa_df$Rater_1,
                           levels = raters,
                              labels = c("a1_r2" = "A1", "a2_r2" = "A2", "naive_bayes" = "NB", "bert" = "BERT", "deberta" = "DeBERTa", "llama_fine-tuned" = "Llama",  "claude_zero-shot" = "Claude", "gpt-oss_zero-shot" = "GPT-OSS"))

kappa_df$Rater_2 <- factor(kappa_df$Rater_2,
                           levels = raters,
                              labels = c("a1_r2" = "A1", "a2_r2" = "A2", "naive_bayes" = "NB", "bert" = "BERT", "deberta" = "DeBERTa", "llama_fine-tuned" = "Llama",  "claude_zero-shot" = "Claude", "gpt-oss_zero-shot" = "GPT-OSS"))

ggplot(kappa_df, aes(x = Rater_1, y = Rater_2, fill = kappa_val))+
  geom_tile()+
  scale_fill_continuous(type = "viridis", name = "kappa")+
  theme_light(base_size = 20)+
    labs(x = "Rater 1",
       y = "Rater 2",
       title = "Relevance classification",
       subtitle = "Inter-rater reliability scores")+
  theme(legend.position = "bottom",
        legend.key.size = unit(1.5,'cm'),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))


```

## Frame detection

```{r}
load("Labelled/Framing_test.RData")

raters <- c("a1_r2", "a2_r2", "naive_bayes", "bert", "deberta", "llama_ft",
            "claude_zero-shot", "gpt-oss_zero-shot")

frames <- c("sexual stigma and transmission routes",
            "racial disparities and stigmatising name",
            "global relations",
            "public health failure",
            "epidemic preparedness and surveillance",
            "human-interest stories",
            "broader health issues")

kappa_df <- expand.grid("Rater_1" = raters,
                        "Rater_2" = raters,
                        "frames" = frames,
                        "kappa_val" = NA,
                        stringsAsFactors = F)

for(i in 1:nrow(kappa_df))
{
  if(kappa_df$Rater_1[i]!=kappa_df$Rater_2[i])
  {
    vec <- calculate_scores(framing_list, kappa_df$Rater_1[i], kappa_df$Rater_2[i], column_A1 = kappa_df$frames[i], column_A2 = kappa_df$frames[i], column_match = "stories_id")
    
    kappa_df$kappa_val[i] <- vec[2]
  }
}

kappa_df$Rater_1 <- factor(kappa_df$Rater_1,
                           levels = raters,
                              labels = c("a1_r2" = "A1", "a2_r2" = "A2", "naive_bayes" = "NB", "bert" = "BERT", "deberta" = "DeBERTa", "llama_ft" = "Llama",  "claude_zero-shot" = "Claude", "gpt-oss_zero-shot" = "GPT-OSS"))

kappa_df$Rater_2 <- factor(kappa_df$Rater_2,
                           levels = raters,
                              labels = c("a1_r2" = "A1", "a2_r2" = "A2", "naive_bayes" = "NB", "bert" = "BERT", "deberta" = "DeBERTa", "llama_ft" = "Llama",  "claude_zero-shot" = "Claude", "gpt-oss_zero-shot" = "GPT-OSS"))


av_df <- aggregate(kappa_df$kappa_val, by = list(kappa_df$Rater_1, kappa_df$Rater_2), FUN = mean)
colnames(av_df) <- c("Rater_1", "Rater_2", "kappa_val")

ggplot(av_df, aes(x = Rater_1, y = Rater_2, fill = kappa_val))+
  geom_tile()+
  scale_fill_continuous(type = "viridis", name = "kappa")+
  theme_light(base_size = 20)+
    labs(x = "Rater 1",
       y = "Rater 2",
       title = "Frame detection",
       subtitle = "Inter-rater reliability scores")+
  theme(legend.position = "bottom",
        legend.key.size = unit(1.5,'cm'),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```
