import collections
import yaml

from datasets import Dataset
import evaluate
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import *
import numpy as np
import pandas as pd
import torch
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, cohen_kappa_score, f1_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForTokenClassification, DataCollatorWithPadding, TrainingArguments, Trainer, pipeline
from transformers import DebertaV2ForSequenceClassification, DebertaV2TokenizerFast
import glob

ENG_STOPWORDS = set(stopwords.words('english'))
CONFIG = yaml.safe_load(open("config.yml"))

class ArticleClassifier(object):
    """
    Base class for relevance classification of text data. 
    Probably don't try to use the base class for anything.
    """
    def __init__(self):
        """
        Sets up a classifier and a (optionally tuneable) threshold for classification
        """
        self.classifier = None # some function that classifies text
        self.threshold = 0.0 # in case we need to tune bias or whatever

    def fit(self, X_train, y_train):
        """
        Will be unique to every child class
        """
        pass

    def accuracy_pr_kappa(self, X_test, y_test):
        """
        Runs the classifier on X_test, which should be an array of texts.
        Compares the classifications it gets to y_test, which is the list of ground truth categorizations for X_test.

        Returns a dict of metrics:
            accuracy
            precision
            recall
            F1 score
            Cohen's Kappa
        """
        guess = self.predict(X_test) # prediction step
        accuracy = accuracy_score(y_test, guess)
        precision = precision_score(y_test, guess)
        recall = recall_score(y_test, guess)
        my_f1_score = f1_score(y_test, guess)
        kappa = cohen_kappa_score(y_test, guess)
        # return a dict of metrics wow
        return {'accuracy': accuracy, 
                'precision': precision, 
                'recall': recall, 
                'f1': my_f1_score, 
                'cohen_kappa': kappa
                }

    def predict(self, X_data):
        """
        Returns a list of classifier predictions; assumes self.classifier is a function/callable that takes in a string.
        """
        return [self.classifier(x) for x in X_data]


class WordRelevanceClassifier(ArticleClassifier):
    """
    Given a list of words and a threshold number of times they should appear in order for the article/keyword list to be considered relevant,
    tag an article or keyword list for relevance.
    """
    def __init__(self, threshold=0, source='keywords', keywords=set(['mpox', 'monkeypox'])):
        """
        Instantiate the class.

        Params:
            threshold: the min number of words that should appear in order for the article/keyword list to be counted as relevant. 
                for keywords, we see each keyword listed once per article. for article text, a word may be repeated and therefore count twice.
            source: one of {keywords, text}. keywords = the keyword list generated by newspaper4k; text = the raw article text
            keywords: a set of lowercase strings corresponding to some keywords that ought to be predictive of relevance.
        """
        self.mpox_keywords = keywords
        self.threshold = threshold
        if source == 'keywords':
            # make an anonymous function that splits up the keyword list (which is a literal of a list) and checks how many of them are in our keyword list
            self.classifier = lambda b: len(set([w.strip() for w in b.lower()[2:-2].split("', '")]).intersection(self.mpox_keywords)) > self.threshold
        elif source == 'text':
            # checks how many times our keywords show up in our article text and compares it to self.threshold.
            self.classifier = lambda b: self.get_counts_from_text(b) > self.threshold
        else:
            raise ValueError("good luck trying to analyze that column buddy")

    def get_counts_from_text(self, text):
        """
        Get the number of times our keywords show up in the text (X instances of word Y = X points)

        text: a string (article text)

        returns: the total number of keyword hits as explained above.
        """
        ct = collections.Counter([w.strip() for w in text.lower().split() if w not in ENG_STOPWORDS])
        tot_hits = sum([ct[k] for k in self.mpox_keywords])
        return tot_hits

    def fit(self, X_train, y_train):
        """
        We aren't actually fitting anything here lol
        """
        raise NotImplementedError("This function is too dumb to have a train function!")

class NBClassifier(ArticleClassifier):
    """
    Naive Bayes classifier for article relevance; can look at keywords or article text.
    """
    def __init__(self, input_type='keywords'):
        """
        Instantiates the object

        Params:
        input_type: lets us know if we're looking at keywords or article text ({'keywords', 'text'} and all others are invalid)
        """
        self.classifier = MultinomialNB() # multinomial Naive Bayes
        self.vectorizer = CountVectorizer(
            strip_accents = 'ascii', 
            lowercase = True,
            stop_words='english', # performs marginally better when stopwords are removed
        )
        if input_type == 'keywords':
            # same text parsing of literal list as before
            self.input_parser = lambda b: b.lower()[2:-2].replace(',', ' ')
        elif input_type == 'text':
            # grab all words that aren't stopwords
            self.input_parser = lambda b: ' '.join([s for s in b.lower().split() if s not in ENG_STOPWORDS])
        else:
            raise ValueError("good luck trying to analyze that column buddy")

    def fit(self, X_train, y_train):
        """
        Given X_train (list of strings, either keywords or article text), and y_train (binary vector),
        train a Naive Bayes classifier to label the strings for relevance.
        """
        # train the vectorizer on training data
        self.vectorizer_fit = self.vectorizer.fit(X_train)
        # vectorize the training data
        x_train_transformed = self.vectorizer_fit.transform(X_train)
        # fit the classifier to the training data
        self.classifier = self.classifier.fit(x_train_transformed, y_train)

    def predict(self, X_data):
        """
        Runs the X_data (list of strings) through the vectorizer and then classifies the resulting count vectors.
        """
        x_transformed = self.vectorizer_fit.transform(X_data)

        return self.classifier.predict(x_transformed)

    def frac_predict(self, X_data):
        """
        Runs the X_data (list of strings) through the vectorizer and then produces a probability for the resulting count vectors.
        """
        x_transformed = self.vectorizer_fit.transform(X_data)

        return self.classifier.predict_proba(x_transformed)

from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForTokenClassification, DataCollatorWithPadding, TrainingArguments, Trainer, pipeline
from transformers import DebertaV2ForSequenceClassification, DebertaV2Tokenizer
from transformers import EarlyStoppingCallback
class DeBERTaClassifier(ArticleClassifier):
    def __init__(self, rel_label, run_save_dir, device='cuda'):
        self.run_save_dir = run_save_dir
        self.rel_label = rel_label
        torch.set_float32_matmul_precision("medium")
        # self.tokenizer = AutoTokenizer.from_pretrained('google-bert/bert-large-cased', use_fast=True)
        # self.model = AutoModelForSequenceClassification.from_pretrained('google-bert/bert-large-cased', num_labels=2)
        self.tokenizer = DebertaV2Tokenizer.from_pretrained("microsoft/deberta-v3-small", model_max_length=512)
        self.model = DebertaV2ForSequenceClassification.from_pretrained("microsoft/deberta-v3-small", num_labels=2)
        self.metric = evaluate.load("f1")
        self.training_args = TrainingArguments(
            output_dir="{}/saved-models-deberta-{}".format(self.run_save_dir, rel_label.replace(' ', '_')),
            overwrite_output_dir=True,
            eval_strategy="steps",
            save_strategy='steps',
            push_to_hub=False,
            num_train_epochs=20,
            per_device_train_batch_size=2,
            per_device_eval_batch_size=2,
            learning_rate=5e-5,
            load_best_model_at_end=True,
            eval_steps = 25,
            save_steps=25,
            save_total_limit = 3,
            save_on_each_node=True,
            metric_for_best_model='f1',

        )
        self.device = device
        self.model.to(self.device)
    def compute_metrics(self, eval_pred):
        logits, labels = eval_pred
        # convert the logits to their predicted class
        predictions = np.argmax(logits, axis=-1)
        return self.metric.compute(predictions=predictions, references=labels)
    def load_best(self):
        save_dir = "{}/saved-models-deberta-{}/checkpoint-*".format(self.run_save_dir, self.rel_label.replace(' ', '_'))
        saved_best = sorted([d for d in glob.glob(save_dir)], key=lambda b: int(b.split('-')[-1]))[0]
        print(saved_best)
        self.model = DebertaV2ForSequenceClassification.from_pretrained(saved_best)
        self.model.to(self.device)
    def make_dataset(self, df):
        df['label'] = df[self.rel_label]
        dataset = Dataset.from_pandas(df[['title', 'text', 'label']])
        return dataset.map(self.tokenize)
    def tokenize(self, examples):
        return self.tokenizer(examples["title"] + '\n' + examples['text'], padding="max_length", truncation=True)
    def train_with_validation(self, df_train, df_val):
        train_tokenized_datasets = self.make_dataset(df_train)
        val_tokenized_datasets = self.make_dataset(df_val)
        trainer = Trainer(
            model=self.model,
            args=self.training_args,
            train_dataset=train_tokenized_datasets,
            eval_dataset=val_tokenized_datasets,
            compute_metrics=self.compute_metrics,
        )
        trainer.train()

    def frac_predict(self, df_test):
        test_dataset = Dataset.from_pandas(df_test[['title', 'text']])
        self.model.eval()
        all_probabilities_v2 = []
        # Process each text
        for example in test_dataset:
            text = f"{example['title']}.\n{example['text']}"
            inputs = self.tokenizer(text, padding=True, truncation=True, return_tensors="pt")
            inputs.to(self.device)
            with torch.no_grad():
                outputs = self.model(**inputs)
            logits = outputs.logits
            probabilities = torch.sigmoid(logits)  # Apply sigmoid to convert logits to probabilities
            all_probabilities_v2.append(probabilities)
        return np.array([v.cpu() for v in all_probabilities_v2])
        
    def predict(self, df_test):
        test_dataset = Dataset.from_pandas(df_test[['title', 'text']])
        self.model.eval()
        all_probabilities_v2 = []
        # Process each text
        for example in test_dataset:
            text = f"{example['title']}.\n{example['text']}"
            inputs = self.tokenizer(text, padding=True, truncation=True, return_tensors="pt")
            inputs.to(self.device)
            with torch.no_grad():
                outputs = self.model(**inputs)
            logits = outputs.logits
            probabilities = torch.sigmoid(logits)  # Apply sigmoid to convert logits to probabilities
            all_probabilities_v2.append(probabilities)
        return np.array([np.argmax(v.cpu()) for v in all_probabilities_v2])

class BERTClassifier(ArticleClassifier):
    def __init__(self, rel_label, run_save_dir, device='cuda'):
        self.rel_label = rel_label
        self.device = device
        self.run_save_dir = run_save_dir
        torch.set_float32_matmul_precision("medium")
        self.tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-large-cased")
        self.model = AutoModelForSequenceClassification.from_pretrained("google-bert/bert-large-cased", num_labels=2)
        self.metric = evaluate.load("f1")
        self.training_args = TrainingArguments(
            output_dir="{}/saved-models-bert-{}".format(self.run_save_dir, rel_label.replace(' ', '_')),
            overwrite_output_dir=True,
            eval_strategy="steps",
            save_strategy='steps',
            push_to_hub=False,
            num_train_epochs=20,
            per_device_train_batch_size=2,
            per_device_eval_batch_size=2,
            learning_rate=5e-5,
            load_best_model_at_end=True,
            eval_steps = 25,
            save_steps=25,
            save_total_limit = 3,
            save_on_each_node=True,
            metric_for_best_model='f1',
        )
        self.model.to(self.device)
        
    def compute_metrics(self, eval_pred):
        logits, labels = eval_pred
        # convert the logits to their predicted class
        predictions = np.argmax(logits, axis=-1)
        return self.metric.compute(predictions=predictions, references=labels)
        
    def make_dataset(self, df):
        df['label'] = df[self.rel_label]
        dataset = Dataset.from_pandas(df[['title', 'text', 'label']])
        return dataset.map(self.tokenize)
        
    def tokenize(self, examples):
        return self.tokenizer(examples["title"] + '\n' + examples['text'], padding="max_length", truncation=True)
            
    def train_with_validation(self, df_train, df_val):
        train_tokenized_datasets = self.make_dataset(df_train)
        val_tokenized_datasets = self.make_dataset(df_val)
        trainer = Trainer(
            model=self.model,
            args=self.training_args,
            train_dataset=train_tokenized_datasets,
            eval_dataset=val_tokenized_datasets,
            compute_metrics=self.compute_metrics,
        )
        trainer.train()
        
    def load_best(self):
        save_dir = "{}/saved-models-bert-{}/checkpoint-*".format(self.run_save_dir, self.rel_label.replace(' ', '_'))
        saved_best = sorted([d for d in glob.glob(save_dir)], key=lambda b: int(b.split('-')[-1]))[0]
        print(saved_best)
        self.model = AutoModelForSequenceClassification.from_pretrained(saved_best)
        self.model.to(self.device)

    def frac_predict(self, df_test):
        test_dataset = Dataset.from_pandas(df_test[['title', 'text']])
        self.model.eval()
        all_probabilities_v2 = []
        # Process each text
        for example in test_dataset:
            text = f"{example['title']}.\n{example['text']}"
            inputs = self.tokenizer(text, padding=True, truncation=True, return_tensors="pt")
            inputs.to(self.device)
            with torch.no_grad():
                outputs = self.model(**inputs)
            logits = outputs.logits
            probabilities = torch.sigmoid(logits)  # Apply sigmoid to convert logits to probabilities
            all_probabilities_v2.append(probabilities)
        return np.array([v.cpu() for v in all_probabilities_v2])
        
    def predict(self, df_test):
        test_dataset = Dataset.from_pandas(df_test[['title', 'text']])
        self.model.eval()
        all_probabilities_v2 = []
        # Process each text
        for example in test_dataset:
            text = f"{example['title']}.\n{example['text']}"
            inputs = self.tokenizer(text, padding=True, truncation=True, return_tensors="pt")
            inputs.to(self.device)
            with torch.no_grad():
                outputs = self.model(**inputs)
            logits = outputs.logits
            probabilities = torch.sigmoid(logits)  # Apply sigmoid to convert logits to probabilities
            all_probabilities_v2.append(probabilities)
        return np.array([np.argmax(v.cpu()) for v in all_probabilities_v2])


class MultiCriterionClassifier(ArticleClassifier):
    """
    Combine the opinions of an arbitrary set of classifiers to arrive at a more informed conclusion.
    """
    def __init__(self, classifiers_with_bools, threshold=None):
        """
        Initialize the classifier.

        Inputs:
            classifers_with_bools: list of (classifier, score_if_relevant) tuples of a RelevanceClassifier object and a boolean value.
            score_if_relevant should be one of {True, False} and should be the score that turns up when an item is relevant.
            threshold: must satisfy strictly more than this number of classifiers in order to be marked relevant.
        """
        self.values_if_relevant = []
        self.classifiers = []
        
        # if no threshold is expressed, everyone has to agree
        if threshold is None:
            self.threshold = len(classifiers_with_bools) - 1
        else:
            # you can also set your own threshold
            self.threshold = threshold

        for clf, val_if_relevant in classifiers_with_bools:
            self.values_if_relevant.append(val_if_relevant)
            self.classifiers.append(clf)

    def predict(self, X_data):
        """
        Given a tuple of inputs as (input_for_clf_1, input_for_clf_2, ...input_for_clf_k),
        run each classifier against its input and then check whether enough classifiers are satisfied with the input's relevance.
        Return pred, a vector of bools.
        """
        pred_bools = np.array([c.predict(x) for c, x in zip(self.classifiers, X_data)])
        pred_scores = [np.sum(row == self.values_if_relevant) for row in pred_bools.T]
        pred = [p > self.threshold for p in pred_scores]
        return pred 

class MultiFrameClassifier(ArticleClassifier):
    def __init__(self, frames, run_save_dir=None, clf_type='NB', device='cuda'):
        self.frames = frames
        self.clf_type = clf_type
        if self.clf_type == "NB":
            self.frame_classifiers = {frame: NBClassifier(input_type='text') for frame in self.frames}
        elif self.clf_type == "BERT":
            if run_save_dir is None:
                raise ValueError("need a run save dir")
            else:
                self.frame_classifiers = {frame: BERTClassifier(frame, run_save_dir, device) for frame in self.frames}
        elif self.clf_type == 'DeBERTa':
            if run_save_dir is None:
                raise ValueError("need a save dir")
            else:
                self.frame_classifiers = {frame: DeBERTaClassifier(frame, run_save_dir, device) for frame in self.frames}
            
    def fit(self, X_train, ys_train, X_val=None, ys_val=None):
        for frame in self.frames:
            if self.clf_type == 'NB':
                self.frame_classifiers[frame].fit(X_train, ys_train[frame])
            elif self.clf_type == "BERT":
                df_train = pd.concat((X_train, ys_train), axis=1)
                df_val = pd.concat((X_val, ys_val), axis=1)
                self.frame_classifiers[frame].train_with_validation(df_train, df_val)
            elif self.clf_type == "DeBERTa":
                df_train = pd.concat((X_train, ys_train), axis=1)
                df_val = pd.concat((X_val, ys_val), axis=1)
                self.frame_classifiers[frame].train_with_validation(df_train, df_val)
                
    def predict(self, X_pred):
        return {frame: self.frame_classifiers[frame].predict(X_pred) for frame in self.frames}

    def frac_predict(self, X_pred):
        return {frame: self.frame_classifiers[frame].frac_predict(X_pred) for frame in self.frames}
        
    def accuracy_pr_kappa(self, X_test, ys_test):
        preds = self.predict(X_test)
        metrics = {}
        for frame in self.frames:
            guess = preds[frame]
            y_test = ys_test[frame]
            accuracy = accuracy_score(y_test, guess)
            precision = precision_score(y_test, guess)
            recall = recall_score(y_test, guess)
            my_f1_score = f1_score(y_test, guess)
            kappa = cohen_kappa_score(y_test, guess)

            metrics[frame] = {
                'accuracy': accuracy,
                'precision': precision,
                'recall': recall,
                'f1': my_f1_score,
                'kappa': kappa,
            }
        return metrics
     
